matrix:
  include:
    - language: node_js
      node_js: 8
      script:
        - yarn && yarn lint && cd reader-sdk-react-native-quickstart && yarn && yarn lint && cd ..

    - language: android
      sudo: false
      jdk: oraclejdk8
      os:
        - linux
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.yarn-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-26
          - android-28
          - extra-google-google_play_services
      install:
        - nvm install 8
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd reader-sdk-react-native-quickstart
        - yarn
      script:
        - cd android
        - ./gradlew clean build -PSQUARE_READER_SDK_APPLICATION_ID=$SQUARE_READER_SDK_APPLICATION_ID -PSQUARE_READER_SDK_REPOSITORY_PASSWORD=$SQUARE_READER_SDK_REPOSITORY_PASSWORD -x :rncamerakit:lint

    - language: objective-c
      os: osx
      osx_image: xcode11
      node_js:
        - 10.16.3
      cache:
        directories:
          - $HOME/.yarn-cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd reader-sdk-react-native-quickstart
        - yarn
        - cd ios && ruby <(curl https://connect.squareup.com/readersdk-installer) install --app-id $SQUARE_READER_SDK_APPLICATION_ID --repo-password $SQUARE_READER_SDK_REPOSITORY_PASSWORD --version 1.1.1 > /dev/null
      script:
        - xcodebuild -workspace RNReaderSDKSample.xcworkspace -configuration Debug -scheme RNReaderSDKSample -destination id=5E2CB2FB-94CC-4DDD-A33F-B11B1771C431 -derivedDataPath build/RNReaderSDKSample
